### ISSUE TITLE
q required at end of command

### ISSUE THREAD

**Issue by joedyndale** [fmtn/a#20]
The following does not work: `./a -p "Testing..." myQueueName`. I need to do the following instead: `./a -p "Testing..." myQueueName q`. No error message is presented. The command says the message was sent, but it was not.

The following commands result in java exceptions stating the parameter name is unknown:

`./a -v`
`./a -l`

But if I do the following they work:

`./a -v q`
`./a -l q`

**Comment by northlander** [comment]
A mysterious % has slipped into the end of the shell-script. Remove the trailing % and it will work as it should. I will update the release to next version.
