### ISSUE TITLE
Can I transform message by js-file?

### ISSUE THREAD

**Issue by armind13** [fmtn/a#22]
Hi. Thanks for this utility!
I try to convert message with command parameter:
`-S @transform.js`
transform.js contains single row:
`msg.stringProperties.set('foo', 'bar');`
But result message hasn't this property in web-console. I tried set jms ttl property and many other, but all time cann't see some changes. 
Can you describe what I should do for insert properties or jms ttl by using transformation with -S?

**Comment by northlander** [comment]
The transform feature seems to not really work during some conditions. For instance when copying/moving messages. It was primarily made to alter messages when reading files from folders and/or creating dump files. However, it should work with copy/move as well. I'll look into it.

**Comment by northlander** [comment]
Fixed a few issues with transformer during copy/move. However, I also noticed that README.md was incorrect. You should use .put, not .set.

Here is an example moving a message while adding the foo=bar property.

```
➜  ~ a -version
A - JMS Test/admin utility specialized for ActiveMQ by Petter Nordlander
Version 1.4.4-SNAPSHOT
GitHub page: https://github.com/fmtn/a
➜  ~ echo "msg.stringProperties.put('foo', 'bar')" > transform.js
➜  ~ a -p "test" q
Message sent
Operation completed in 10ms (excluding connect)
➜  ~ a -S @transform.js -M q q2
1 msgs moved from q to q2
Operation completed in 214ms (excluding connect)
➜  ~ a q2
-----------------
Message Properties
  foo: bar
Payload:
test
Operation completed in 13ms (excluding connect)
```
