### ISSUE TITLE
Provide built .jar package for download

### ISSUE THREAD

**Issue by mtausk** [fmtn/a#221]
Hi,

At datacenters behind firewall it is impossible to download maven and .jar package would be appreciated.

Please, provide a way to download the a.jar package, if possible.

Thanks.

**Comment by northlander** [comment]
The release page always contain a compressed file with start script and .jar file.

For instance, at https://github.com/fmtn/a/releases/tag/v1.6.0 you will find [a-1.6.0-dist.tar.gz](https://github.com/fmtn/a/releases/download/v1.6.0/a-1.6.0-dist.tar.gz) and [a-1.6.0-dist.zip](https://github.com/fmtn/a/releases/download/v1.6.0/a-1.6.0-dist.zip) - same file just pick the easiest to unzip on your platform
