### ISSUE TITLE
Do you need a logo?

### ISSUE THREAD

**Issue by nunojesus** [fmtn/a#25]
Hi Hello I am looking for open source projects to contribute graphical design, I have done several jobs for free in opensource projects, I would like to know if you are interested that I make a logo for this your project ?.

Greetings

Nuno Jesus

**Comment by northlander** [comment]
Hi! Sure, why not? This is just a small open source utility, but if you want to contribute a logo - go for it!

**Comment by nunojesus** [comment]
Great!

So let´s begin, do you have any request for the logo? Shape? Colors?

It´s only for desktop, are you thinking to make a app to android and ios too?

Greetings!

**Comment by northlander** [comment]
It's a simple desktop/cmd utility, no mobile apps. I haven't thought about a logo, less so any shape. But for colors, black and yellow are preferred.

**Comment by nunojesus** [comment]
Hello, Im thinking to make a logo with the letter A, since is the name of the project, do you like something more minimalist or something with much color?

Greetings.

**Comment by nunojesus** [comment]
Since A is a JMS testing/admin what do you think that I create a logo with letter A and a check mark?

**Comment by nunojesus** [comment]
See if you like one of this logos
![avector](https://user-images.githubusercontent.com/34600369/40329090-58e584e2-5d40-11e8-9973-526e43a26c31.png)

**Comment by northlander** [comment]
The top one is awesome! :-) Really!

**Comment by nunojesus** [comment]
Im happy that you like it, as I say it the concept for this logo was the Letter A with a check mark, the colors I chose are the black and yellow that you requested.
So não I will make a pull request with the files.

greetings!

**Comment by northlander** [comment]
Great! thx
