### ISSUE TITLE
mvn clean install failing on tests for both master and feature/java8 

### ISSUE THREAD

**Issue by chines** [fmtn/a#40]
Hello,

First, thanks for such a cool tool!   I'm using it for random sorts of automation on our ActiveMQ servers.

When I try to git clone and then mvn clean install, it fails due to:

Tests in error: 
  testPutTopic(co.nordlander.a.AOpenWireTest)

I'm not sure exactly where to find the specific error -- this is the only thing I can see around the start of the tests:

Running co.nordlander.a.AOpenWireTest

0 messages cleared from queue://TARGET.QUEUE
0 messages cleared from queue://TEST.QUEUE
0 messages cleared from queue://SOURCE.QUEUE
Testing cmd: -b tcp://localhost:61916 -p "test-PLACEHOLDER" -W /tmp/junit7298892113214240993/junit661030776037202266/batch.txt -S "msg.body=msg.body.replace('PLACEHOLDER',entry);" TEST.QUEUE
3 messages sent
Message sent
Operation completed in 230ms (excluding connect)
0 messages cleared from queue://TARGET.QUEUE
0 messages cleared from queue://TEST.QUEUE
0 messages cleared from queue://SOURCE.QUEUE
4 msgs moved from SOURCE.QUEUE to TARGET.QUEUE
Operation completed in 52ms (excluding connect)
0 messages cleared from queue://TARGET.QUEUE
0 messages cleared from queue://TEST.QUEUE
0 messages cleared from queue://SOURCE.QUEUE
Writing 1 messages to dump file /tmp/junit7725678142798527935/junit998083138520055583/dump.json
Failed to write all messages to dump file. Reason: ReferenceError: "dummy" is not defined in <eval> at line number 1
Rolling back JMS transaction

**Comment by northlander** [comment]
Had this issue with some travis builds as well. It's test related. Hopefully it's gone with a major update of libraries. If it appears again, I will try to fix it.

**Comment by northlander** [comment]
Perhaps a race condition anyway. A slight delay may make sure the subscription kicks in before. Can't confirm it yet though. Let's see if 1.5.0 builds better with this fix in place.

**Comment by northlander** [comment]
Closing, will reopen if this returns
