### ISSUE TITLE
Browse Limited to 400 messages?

### ISSUE THREAD

**Issue by tledwar** [fmtn/a#44]
I recently discovered a fairly large dead letter queue and am trying too output (not dump; yet) the messages to files. When I run java -jar a-1.4.8-jar-with-dependencies.jar -b "ssl://localhost:61617" -U "procellaworkers" -P "dm9YDfSMKEKA0WB7qMcFkjoVKawOkuzw" ActiveMQ.DLQ -c 0 -j -o "messages/dlq" the output stops at 400. 

I am concerned that if I do use dump in the future, that it will also be limited to 400.

**Comment by tledwar** [comment]
I now see that ActiveMQ has maxBrowsePageSize which defaults to 400. See: https://activemq.apache.org/per-destination-policies

I see you mention this in -C for copy queue, but not elsewhere. 

Can this be changed in your client or do we have to change this in the Broker itself on the server?

**Comment by tledwar** [comment]
I have attempted to use Dump and only receive a single message.

**Comment by faabsen** [comment]
Have you tried the dump option wie the paramter "-c 0"?

**Comment by northlander** [comment]
There is nothing more to add to this. maxBrowsePageSize is the only way to browse more messages.
