### ISSUE TITLE
Warning: Nashorn engine is planned to be removed from a future JDK release

### ISSUE THREAD

**Issue by oDevArc** [fmtn/a#71]
Hi,

Since my upgrade to Fedora 33 I have this message : `Warning: Nashorn engine is planned to be removed from a future JDK release` using `-x` and `-X` options

are you aware of this issue for future version ?

**Comment by erwindon** [comment]
which version of "a" are you using?
an option to suppress this warning was added in 4ff0e1e0f2ea5b850a97d57479bf005f90139149 (22-dec-2019)

**Comment by oDevArc** [comment]
thank's a lot for your answer and very sorry for the delay
